name: "Clang Static Analyzer"

on:
  pull_request:
    paths:
      - '**/*.c'
      - '**/*.h'
      - 'grammar/lexer.l'
      - 'grammar/grammar.y'
      - 'devtools/run-static-analyzer.sh' # run on change of analyzer script itself
      - '.github/workflows/clang-analyzer.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  clang-analyzer:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run clang static analyzer
        id: run-clang
        env:
          RSYSLOG_DEV_CONTAINER: rsyslog/rsyslog_dev_base_ubuntu:24.04
          SCAN_BUILD: scan-build
          SCAN_BUILD_CC: clang
          SCAN_BUILD_REPORT_DIR: scan-build-report
          DOCKER_RUN_EXTRA_OPTS: >-
            -e SCAN_BUILD -e SCAN_BUILD_CC -e SCAN_BUILD_REPORT_DIR
        run: |
          chmod -R go+rw .
          set +e
          devtools/devcontainer.sh --rm devtools/run-static-analyzer.sh 2>&1 | tee clang-analyzer.log
          echo "exitcode=${PIPESTATUS[0]}" >> $GITHUB_OUTPUT

      - name: Upload clang static analyzer report
        if: always()
        id: upload-report
        uses: actions/upload-artifact@v4
        with:
          name: clang-static-analyzer-report
          path: scan-build-report
          retention-days: 7
          if-no-files-found: ignore   # optional: prevents failure if dir absent

      - name: Show clang static analyzer report link
        if: always()
        run: |
          artifact=${{ steps.upload-report.outputs.artifact-url }}
          cat >> $GITHUB_STEP_SUMMARY <<EOF
          Clang static analyzer HTML report (download):
          $artifact
          EOF
          echo "Clang static analyzer HTML report (download):"
          echo "$artifact"

      - name: Fail if analysis failed
        if: steps.run-clang.outputs.exitcode != '0'
        run: |
          artifact="${{ steps.upload-report.outputs.artifact-url }}"
          echo "clang static analyzer detected issues:" >&2
          tail -n 200 clang-analyzer.log >&2 || true
          echo >&2
          echo "Clang static analyzer HTML report (download): $artifact" >&2
          exit 1

